name: pin_code_fields_example
description: Example app demonstrating pin_code_fields package.
publish_to: 'none'

environment:
  sdk: ^3.5.4
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pin_code_fields:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
